// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class Event
{
    public int EventId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }
    public DateTime RegistrationClosingDate { get; set; }
    public string EventName { get; set; }
    public string EventDescription { get; set; }
    public bool RegistrationClosed { get; set; }

    public int FkOrganizerId { get; set; }

    public virtual Player FkOrganizer { get; set; }

    public virtual ICollection<Player> FkPlayers { get; set; } = new List<Player>();
}