// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class Game
{
    public int GameId { get; set; }

    public string GameName { get; set; }

    public int PlayersMin { get; set; }

    public int PlayersMax { get; set; }

    public int AverageDuration { get; set; }

    public int AgeMin { get; set; }

    public string Picture { get; set; }

    public string GameDescription { get; set; }

    public string Video { get; set; }

    public int? FkThemeId { get; set; }

    public bool? IsExtension { get; set; }

    public virtual Theme FkTheme { get; set; }

    public virtual ICollection<PlayerGame> PlayerGames { get; set; } = new List<PlayerGame>();

    public virtual ICollection<Keyword> FkKeywords { get; set; } = new List<Keyword>();

    public virtual ICollection<Theme> FkSecondaryThemes { get; set; } = new List<Theme>();
}

public class GameRequest
{
    public string GameName { get; set; }
    public int PlayersMin { get; set; }
    public int PlayersMax { get; set; }
    public int AverageDuration { get; set; }
    public int AgeMin { get; set; }
    public string Picture { get; set; }
    public string GameDescription { get; set; }
    public string Video { get; set; }
    public int? FkThemeId { get; set; }
    public bool? IsExtension { get; set; }
    public List<int> FkKeywordsId { get; set; } // Liste d'IDs de mots-clés
}

