// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class Keyword
{
    public int KeywordId { get; set; }

    public string KeywordName { get; set; }

    public string KeywordDescription { get; set; }

    public virtual ICollection<PlayerKeyword> PlayerKeywords { get; set; } = new List<PlayerKeyword>();

    public virtual ICollection<Game> FkGames { get; set; } = new List<Game>();
}