// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class PlayerTheme
{
    public int FkThemeId { get; set; }

    public int FkPlayerId { get; set; }

    public int? ThemeNote { get; set; }

    public virtual Player FkPlayer { get; set; }

    public virtual Theme FkTheme { get; set; }
}