// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class PlayerGame
{
    public int PlayerGameId { get; set; }

    public int? FkPlayerId { get; set; }

    public int? FkGameId { get; set; }

    public int NumberPossessed { get; set; }

    public bool Eligible { get; set; }

    public virtual Game FkGame { get; set; }

    public virtual Player FkPlayer { get; set; }
}