// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class PlayerKeyword
{
    public int FkKeywordId { get; set; }

    public int FkPlayerId { get; set; }

    public int? KeywordNote { get; set; }

    public virtual Keyword FkKeyword { get; set; }

    public virtual Player FkPlayer { get; set; }
}