// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lutoftheque.Entity.Models;

public partial class Theme
{
    public int ThemeId { get; set; }

    public string ThemeName { get; set; }

    public string ThemeDescription { get; set; }

    public virtual ICollection<Game> Games { get; set; } = new List<Game>();

    public virtual ICollection<PlayerTheme> PlayerThemes { get; set; } = new List<PlayerTheme>();

    public virtual ICollection<Game> FkGames { get; set; } = new List<Game>();
}